// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagement.Infrastructure.Data;

#nullable disable

namespace StudentManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260722181005_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagement.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 21,
                            Course = "Computer Science",
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "aarav.sharma@example.com",
                            Name = "Aarav Sharma"
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            Course = "Information Technology",
                            CreatedDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "priya.patel@example.com",
                            Name = "Priya Patel"
                        },
                        new
                        {
                            Id = 3,
                            Age = 20,
                            Course = "Data Science",
                            CreatedDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "rohan.verma@example.com",
                            Name = "Rohan Verma"
                        });
                });

            modelBuilder.Entity("StudentManagement.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@zestindia.com",
                            PasswordHash = new byte[] { 137, 186, 67, 37, 170, 43, 222, 185, 16, 63, 49, 52, 67, 143, 150, 91, 152, 231, 238, 49, 193, 61, 255, 242, 116, 83, 96, 127, 108, 61, 10, 131, 203, 103, 87, 146, 109, 131, 224, 135, 105, 123, 214, 26, 76, 115, 219, 100, 214, 157, 58, 26, 135, 97, 132, 118, 49, 179, 62, 67, 39, 101, 124, 69 },
                            PasswordSalt = new byte[] { 213, 80, 167, 73, 47, 230, 14, 89, 98, 195, 241, 205, 152, 74, 79, 74, 96, 113, 77, 203, 244, 113, 194, 132, 81, 2, 199, 202, 161, 183, 38, 93, 226, 106, 154, 16, 95, 243, 55, 217, 221, 185, 42, 103, 245, 41, 98, 22, 223, 73, 174, 167, 44, 97, 139, 220, 184, 208, 242, 55, 208, 225, 59, 6, 185, 71, 136, 15, 190, 14, 245, 2, 153, 71, 247, 149, 116, 144, 190, 3, 228, 219, 173, 139, 182, 172, 140, 75, 243, 114, 210, 198, 25, 72, 179, 188, 112, 93, 208, 157, 84, 199, 209, 117, 249, 51, 136, 198, 46, 223, 196, 52, 10, 83, 145, 117, 178, 244, 125, 128, 34, 147, 205, 136, 250, 240, 193, 90 },
                            Role = "Admin",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
